// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXUCAeVhkUJQXj4EVnO2LV2ldwBVq6g7Y',
    appId: '1:346989270016:web:1eeb5fc0284ffc515574e5',
    messagingSenderId: '346989270016',
    projectId: 'rent-app-mkpro',
    authDomain: 'rent-app-mkpro.firebaseapp.com',
    storageBucket: 'rent-app-mkpro.firebasestorage.app',
    measurementId: 'G-K7MBQ3CQW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTCSP1Uu3YJeAh-Yae7iCM4XS7QlxB1KA',
    appId: '1:346989270016:android:9d1c74c0de6a1c345574e5',
    messagingSenderId: '346989270016',
    projectId: 'rent-app-mkpro',
    storageBucket: 'rent-app-mkpro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqcWRRbKWzQHbJjvF77TYHDO7NVhYXUVQ',
    appId: '1:346989270016:ios:8bf2677a720f4fd05574e5',
    messagingSenderId: '346989270016',
    projectId: 'rent-app-mkpro',
    storageBucket: 'rent-app-mkpro.firebasestorage.app',
    iosBundleId: 'com.example.rentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqcWRRbKWzQHbJjvF77TYHDO7NVhYXUVQ',
    appId: '1:346989270016:ios:8bf2677a720f4fd05574e5',
    messagingSenderId: '346989270016',
    projectId: 'rent-app-mkpro',
    storageBucket: 'rent-app-mkpro.firebasestorage.app',
    iosBundleId: 'com.example.rentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXUCAeVhkUJQXj4EVnO2LV2ldwBVq6g7Y',
    appId: '1:346989270016:web:785825e633f2a4365574e5',
    messagingSenderId: '346989270016',
    projectId: 'rent-app-mkpro',
    authDomain: 'rent-app-mkpro.firebaseapp.com',
    storageBucket: 'rent-app-mkpro.firebasestorage.app',
    measurementId: 'G-2BY1X33BNH',
  );
}
